### ISSUE TITLE
differences with redux dev-tools?

### ISSUE THREAD

**Issue by dcsan** [open-source-labs/reactime#167]
sorry for non-tech issue, but it might improve your install funnel if you could be clear about the differences vs. redux devtools, which a lot of people use already?
at first glance they look pretty similar, time-travel debugging etc.

https://github.com/zalmoxisus/redux-devtools-extension

![](https://cloud.githubusercontent.com/assets/7957859/18002950/aacb82fc-6b93-11e6-9ae9-609862c18302.png)

![image](https://user-images.githubusercontent.com/514002/76153949-d135bc80-6088-11ea-8b13-0b4e88b7fc66.png)

and they have various fancy features like state 'chart'

also why does this require an NPM package to be installed, as opposed to just working as a chrome extension?

**Comment by davidchai717** [comment]
Hi @dcsan , great question. Reactime is targeted towards **React-only** (think components using this.state or hooks) projects, whereas Redux DevTools is meant for those that use Redux for state management. With that said, we are essentially inspired by them as the primary goal of this tool is to bring time traveling over to React. In order to do that as a third-party tool, however, we would need direct access to the component tree of user's application. Hope that's helpful!

**Comment by dcsan** [comment]
thanks for the reply. If I *am* using redux, does this tool give any extra insights? there is still a level of detail missing in terms of the order of when selectors get updated but that's deep into redux land I guess.

good luck with it and thanks for open-sourcing!
