### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded in backend.bundle.js

### ISSUE THREAD

**Issue by kerenren** [open-source-labs/reactime#250]
Hi recently I got this error when I open my react app in development mode:
![image](https://user-images.githubusercontent.com/62934991/137908071-8c51d08c-eacc-4985-a6a2-1593ed02c1bf.png)

It seems this function S has been called in an infinity loop 
![image](https://user-images.githubusercontent.com/62934991/137912388-ca8459fd-b47b-4591-88ad-7461307a5fac.png)

Perfomace record: 
![image](https://user-images.githubusercontent.com/62934991/137912143-595bb6b6-f1d2-49ab-8849-5593f4d10678.png)

More details:

React v17.0.2
Redux v4.0.4
redux-thunk v2.3.0
React-Redux v7.1.0

**Comment by Elyx0** [comment]
Same problem.
Reactime
11.0.0

React Developer Tools
4.21.0 (10/31/2021)

Gatsby 3.14
<img width="1262" alt="Screen Shot 2021-11-30 at 12 41 24 AM" src="https://user-images.githubusercontent.com/706218/143992227-57d9cb39-30b7-4318-a8e0-a6f8c247a302.png">

**Comment by mapsgeek** [comment]
same on Nextjs setup

**Comment by aspiers** [comment]
I have proposed a fix for this in #257.  It seems to work fine for me.  Would be great if others could test it and report back here.  If you don't know how, please see #255 (and also #253, #254).

**Comment by deadcoder0904** [comment]
same error made me lost a lot of time. i thought something was wrong with my code but it was the extension. plz fix it. i'll disable it until then :)

**Comment by fahad-attech** [comment]
> same error made me lost a lot of time. i thought something was wrong with my code but it was the extension. plz fix it. i'll disable it until then :)

Same

**Comment by aspiers** [comment]
Or you could try the fix I proposed above ;-)

**Comment by tyfiero** [comment]
This error is still happening for me, makes the extension unusable, unfortunately. I'm using Next.js 12.2 and React 18. If @aspiers has a fix, why not implement it?

**Comment by jemzir** [comment]
Implemented a depth limiter in v17.0 that should now fix that issue!

**Comment by jemzir** [comment]
Implemented a depth limiter that should now fix this issue in v17.0.0!

**Comment by aspiers** [comment]
@jemzir I submitted a depth limiter fix in 2021 (see #257 as mentioned above) but it seems like no one reviewed it yet.  It would be really nice if all the fixes I submitted a long time ago could be reviewed - perhaps then you could save time having to duplicate the same fixes yourself.  There are [5 PRs I submitted which are still open](https://github.com/open-source-labs/reactime/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aaspiers).  Thanks for your consideration!

**Comment by benmarg** [comment]
Hi @aspiers, we did actually implement that fix in this release! You're contributions were incredibly clutch, sorry it took the team so long get around to implementing them! We're going to be closing the corresponding PRs to the solutions we managed to implement this release shortly. Thanks again so much!

**Comment by aspiers** [comment]
Glad to hear you've found them useful :-)  But I'm a bit puzzled why there was any need to reimplement this fix I submitted instead of just merging it?  I submitted the fix in #257 on Dec 11 2021, and I see that the exact same code change was committed a year later in fdb65c58e, without my name or email as the git committer, and without the explanation I took the time to write in my commit message.  Meanwhile #257 has gone over two years without any feedback at all.

Apologies if this sounds a bit petty, especially since I know this is a tiny code change - but it's the principle behind it which I want to highlight.  TBH it's a bit demoralising when I go to the effort of implementing a fix and even documenting it nicely, and then it gets reimplemented without any trace in the git history of my contribution.  In that kind of scenario, there's no evidence that I saved anyone else's time, or that I didn't waste my own.  Please don't get me wrong - I'm quite sure there was zero ill intentions here!  And also I know how hard it is to find spare time to maintain F/OSS projects; I do it myself, and sometimes I don't do a great job, so I can't even claim to fully practice what I preach.

But if you want to keep encouraging contributions from the wider community, as much as possible I'd recommend trying to give contributors the satisfaction of seeing our commits merged into the git history.  I don't ask for anything else, but that feeling of having proof I contributed is a little feel-good kick which motivates me to do it in the first place, and I'm pretty sure a lot of other F/OSS contributors feel the same :-)

Hope that makes sense, and thanks for listening!
